import "./globals.css";
import type { Metadata } from "next";
import { Jacques_Francois } from "next/font/google";

const jacques_Francois = Jacques_Francois({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-secondary scroll-smooth">
      <body className={jacques_Francois.className}>{children}</body>
    </html>
  );
}
